// <auto-generated />
using System;
using F1Palpiteiros.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1Palpiteiros.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427133130_SeasonNameStringLimit")]
    partial class SeasonNameStringLimit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("F1Palpiteiros.Model.Championship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Championships");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.ChampionshipDriver", b =>
                {
                    b.Property<long>("ChampionshipId")
                        .HasColumnType("bigint");

                    b.Property<long>("DriverId")
                        .HasColumnType("bigint");

                    b.HasKey("ChampionshipId", "DriverId");

                    b.HasIndex("DriverId");

                    b.ToTable("ChampionshipDriver");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.CompetitorStanding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChampionshipId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Points")
                        .HasColumnType("real");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChampionshipId");

                    b.HasIndex("UserId");

                    b.ToTable("CompetitorStandings");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.Driver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainDriver")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.Guess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("GuessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PointsEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<long?>("RaceWeekEventId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RaceWeekEventId");

                    b.HasIndex("UserId");

                    b.ToTable("Guesses");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.RaceWeek", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ChampionshipId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChampionshipId");

                    b.ToTable("RaceWeeks");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.RaceWeekEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChampionshipId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RaceWeekId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChampionshipId");

                    b.HasIndex("RaceWeekId");

                    b.ToTable("RaceWeekEvents");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.Suggestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DriverId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuessId")
                        .HasColumnType("bigint");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("GuessId", "Position")
                        .IsUnique();

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.ChampionshipDriver", b =>
                {
                    b.HasOne("F1Palpiteiros.Model.Championship", "Championship")
                        .WithMany("Drivers")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Palpiteiros.Model.Driver", "Driver")
                        .WithMany("Championships")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Championship");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.CompetitorStanding", b =>
                {
                    b.HasOne("F1Palpiteiros.Model.Championship", "Championship")
                        .WithMany("Competitors")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Palpiteiros.Model.User", "User")
                        .WithMany("CompetitorStandings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Championship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.Guess", b =>
                {
                    b.HasOne("F1Palpiteiros.Model.RaceWeekEvent", null)
                        .WithMany("Guesses")
                        .HasForeignKey("RaceWeekEventId");

                    b.HasOne("F1Palpiteiros.Model.User", "User")
                        .WithMany("Guesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.RaceWeek", b =>
                {
                    b.HasOne("F1Palpiteiros.Model.Championship", "Championship")
                        .WithMany("RaceWeeks")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Championship");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.RaceWeekEvent", b =>
                {
                    b.HasOne("F1Palpiteiros.Model.Championship", null)
                        .WithMany("Events")
                        .HasForeignKey("ChampionshipId");

                    b.HasOne("F1Palpiteiros.Model.RaceWeek", "RaceWeek")
                        .WithMany("Events")
                        .HasForeignKey("RaceWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaceWeek");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.Suggestion", b =>
                {
                    b.HasOne("F1Palpiteiros.Model.Driver", "Driver")
                        .WithMany("Suggestions")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("F1Palpiteiros.Model.Guess", "Guess")
                        .WithMany("Suggestions")
                        .HasForeignKey("GuessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Guess");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.Championship", b =>
                {
                    b.Navigation("Competitors");

                    b.Navigation("Drivers");

                    b.Navigation("Events");

                    b.Navigation("RaceWeeks");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.Driver", b =>
                {
                    b.Navigation("Championships");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.Guess", b =>
                {
                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.RaceWeek", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.RaceWeekEvent", b =>
                {
                    b.Navigation("Guesses");
                });

            modelBuilder.Entity("F1Palpiteiros.Model.User", b =>
                {
                    b.Navigation("CompetitorStandings");

                    b.Navigation("Guesses");
                });
#pragma warning restore 612, 618
        }
    }
}
